<?php
    /*!
     *
     * Copyright © 2010 James Newton <james@Zaphyous.com>. All Rights Reserved.
     *
     */

    /*!
     * 
     * IP's that are not allowed to use derp
     *
     */

    $disallow_ip = array(
    );

    /*!
     *
     * URL's that are not allowed on derp
     *
     */

    $disallow_url = array(
        ".*\.on\.nimp\.org"
    );

    /*!
     *
     * id's that cannot be used for pastes
     *
     */

    $disallow_id = array(
        "css",
        "data",
        "inc",
        "js",
        "pages",
        "search",
        "download",
        "login",
        "rss",
        "report",
        "gui"
    );

    /*!
     *
     * advertisements
     *
     */

    $advert = array(
    );
?>
